name: Python CI (Lint & Doctests)

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      # ---------------------------
      # LINTING & FORMAT CHECK
      # ---------------------------
      #- name: Code automatisch formatieren
      #  run: |
      #    black .

      #- name: Style-Check (flake8)
      #  run: |
      #    flake8 .


      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39
        continue-on-error: true

      # ---------------------------
      # TESTS (inkl. DOCTESTS)
      # ---------------------------
      - name: Alle Tests ausführen
        run: |
           pytest --doctest-glob="*.py" --doctest-modules